---
baseURL: padukuhanbanjeng.com
title: Padukuhan Banjeng
paginate: "6"
summaryLength: "10"
disableLanguages: []
enableRobotsTXT: true
params:
  instagrams:
    appId: ''
    clientToken: ''
  plugins:
    css:
    - link: "/plugins/bootstrap/bootstrap.min.css"
    - link: "/plugins/slick/slick.css"
    - link: "/plugins/animate/animate.css"
    - link: "/plugins/venobox/venobox.css"
    - link: "/plugins/themify-icons/themify-icons.css"
    js:
    - link: "/plugins/jQuery/jquery.min.js"
    - link: "/plugins/bootstrap/bootstrap.min.js"
    - link: "/plugins/slick/slick.min.js"
    - link: "/plugins/venobox/venobox.min.js"
    - link: "/plugins/filterizr/jquery.filterizr.min.js"
  logo: images/logo.png
  description: This is meta description
  author: Themefisher
  address: 
  mobile: ''
  email: padukuhanbanjeng@gmail.com
  contact_form_action: "/contact"
  google_analitycs_id: ''
  top_header: false
  preloader:
    enable: false
    preloader: images/preloader.gif
  subscription:
    enable: false
    mailchimp_form_action: https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074
    mailchimp_form_name: b_463ee871f45d2d93748e77cad_a0a2c6d074
  map:
    enable: true
    gmap_api: https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places
    map_latitude: "-0.4269341976387936"
    map_longitude: "117.16266208698144"
    map_marker: images/marker.png
  cookies:
    enable: true
    expire_days: 2
  social: []
Languages:
  en:
    languageName: En
    languageCode: en-us
    contentDir: content/
    weight: 1
    copyright: Copyright &copy; 2022 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)
    menu:
      main:
      - parent: Profil
        weight: 1
        name: Demografi
        url: demografi/
      - parent: Profil
        weight: 2
        name: Visi, Misi & Slogan
        url: visimisi/
      - parent: Profil
        weight: 3
        name: Profil Kepala Dukuh
        url: kepaladukuh/
      - name: Inovasi Desa
        weight: 2
        hasChildren: true
        url: ''
      - parent: Inovasi Desa
        weight: 1
        name: Padukuhan Literasi
        url: literasi/
      - parent: Inovasi Desa
        weight: 2
        name: Kampung KB
        url: kampungkb/
      - parent: Inovasi Desa
        weight: 3
        name: Posyandu
        url: posyandu/
      - parent: Inovasi Desa
        weight: 4
        name: Perikanan
        url: perikanan/
      - parent: Inovasi Desa
        weight: 5
        name: Taman WMB Banjeng
        url: taman/
      - parent: Inovasi Desa
        weight: 6
        name: Perternakan
        url: perternakan/
      - parent: Inovasi Desa
        weight: 7
        name: UMKM
        url: umkm/
      - name: Galeri
        weight: 5
        hasChildren: true
        url: ''
      - parent: Galeri
        weight: 3
        name: Dusun Banjeng
        url: dusunbanjeng/
      - parent: Galeri
        weight: 2
        name: Dusun Tempelsari
        url: dusuntempelsari/
      - parent: Galeri
        weight: 3
        name: Dusun Grogol
        url: dusungrogol/
      - parent: Galeri
        weight: 4
        name: Dusun Bokoharjo
        url: dusunbokoharjo/
      - parent: Galeri
        weight: 5
        name: Ayodya Citra
        url: ayodyacitra/
      - name: Profil
        weight: 4
        hasChildren: true
        url: ''
      helper:
      - name: Netlify
        url: https://app.netlify.com/sites/padukuhanbanjeng/overview
      - name: Forestry (Admin)
        url: https://app.forestry.io/sites/54h9udufzrvucq/
metaDataFormat: yaml
