backend:
  name: git-gateway
  branch: main

local_backend: true
publish_mode: editorial_workflow
use_large_media_transforms_in_media_library: false
media_folder: "static/images"
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit
  - name: "acara"
    label: "Acara"
    folder: "content/acara"
    create: true
    identifier_field: name
    media_folder: "/static/images/events"
    public_folder: "images/events"
    fields:
      - {label: "Judul Acara", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "string"}
      - {label: "Harga", name: "fee", widget: "string"}
      - {label: "Link Pendaftaran", name: "apply_url", widget: "string", default: "#"}
      - {label: "Lokasi", name: "location", widget: "string"}
      - {label: "Tanggal Di Upload", name: "publishDate", widget: "datetime"}
      - {label: "Tanggal Acara", name: "date", widget: "datetime"}
      - {label: "Masukkan Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Poster Untuk Event", name: "image", widget: "image"}
      - {label: "Tipe", name: "type", widget: "hidden", default: "event"}
      - label: "Pembicara"
        name: "speaker"
        widget: "list"
        fields: 
          - {label: "Nama Pembicara", name: "name", widget: "string"}
          - {label: "Gambar Pembicara", name: "image", widget: "image", default: "/event-speakers/speaker-1.jpg"}
          - {label: "Gelar/Penamaan", name: "designation", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog Artikel"
    folder: "content/blog"
    create: true
    identifier_field: name
    media_folder: "/static/images/blog/"
    public_folder: "images/blog"
    fields:
      - {label: "Judul Blog", name: "title", widget: "string", default: "Judul Artikel"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Masukkan Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image", default: "images/backgrounds/page-title.jpg"}
      - {label: "Penulis", name: "author", widget: "string", default: "John Doe"}
      - {label: "Kategori", name: "kategori", widget: "string"}
      - {label: "Topik", name: "topik", widget: "list"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Gambar", name: "image", widget: "image", default: "images/blog/post-1.jpg"}
      - {label: "Deskripsi", name: "dscription", widget: "string", default: "Ini adalah deskripsi"}
      - {label: "Isi Artikel", name: "body", widget: "markdown"}
  
  - name: "pasar"
    label: "Pasar"
    folder: "content/pasar"
    create: true
    identifier_field: name
    media_folder: "/static/images/courses"
    public_folder: "images/courses"
    fields:
      - {label: "Nama Dagangan", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "string"}
      - {label: "Harga", name: "fee", widget: "string"}
      - {label: "Alamat", name: "location", widget: "string"}
      - {label: "Link Kontak", name: "apply_url", widget: "string"}
      - {label: "Nama Penjual", name: "seller", widget: "string"}
      - {label: "Jam Buka", name: "duration", widget: "string", default: "07:00 - 13:00"}
      - {label: "Hari Buka", name: "open", widget: "string", default: "Senin - Jum'at"}
      - {label: "Tanggal Di Upload", name: "date", widget: "datetime"}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Poster Untuk Dagangan", name: "image", widget: "image"}
      - {label: "Masukkan Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Tipe", name: "type", widget: "hidden", default: "pasar"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "tentang"
    label: "Tentang"
    folder: "content/about"
    create: false
    identifier_field: name
    media_folder: "/static/images/about"
    public_folder: "images/about"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}
      - label : "Data Desa"
        name  : "village_data"
        widget: "list"
        fields:
          - {label: "Nama Data", name: "name", widget: "string"}
          - {label: "Jumlah Data", name: "count", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  # - name: "staff"
  #   label: "Staff"
  #   folder: "content/english/staff"
  #   create: true
  #   identifier_field: name
  #   media_folder: "/static/images/teachers"
  #   public_folder: "images/teachers"
  #   fields:
  #     - {label: "Nama Staf", name: "title", widget: "string"}
  #     - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
  #     - {label: "Deskripsi", name: "description", widget: "hidden"}
  #     - {label: "Foto Staf", name: "image", widget: "image", default: "images/teachers/syahril.jpg"}
  #     - {label: "Jabatan/Bagian", name: "course", widget: "string"}
  #     - {label: "Bio", name: "bio", widget: "string"}
  #     - {label: "Hobi", name: "interest", widget: "list"}
  #     - {label: "Body", name: "body", widget: "markdown"}

