backend:
  name: git-gateway
  branch: main

local_backend: true
publish_mode: editorial_workflow
use_large_media_transforms_in_media_library: false
media_folder: "static/images"
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit
  - name: "blog"
    label: "Blog Artikel"
    folder: "content/blog"
    create: true
    identifier_field: name
    media_folder: "/static/images/blog/"
    public_folder: "images/blog"
    fields:
      - {label: "Judul Blog", name: "title", widget: "string", default: "Judul Artikel"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Masukkan Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image", default: "images/backgrounds/page-title.jpg"}
      - {label: "Penulis", name: "author", widget: "string", default: "John Doe"}
      - {label: "Kategori", name: "kategori", widget: "string"}
      - {label: "Topik", name: "topik", widget: "list"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Gambar", name: "image", widget: "image", default: "images/blog/post-1.jpg"}
      - {label: "Deskripsi", name: "dscription", widget: "string", default: "Ini adalah deskripsi"}
      - {label: "Isi Artikel", name: "body", widget: "markdown"}
  
  - name: "demografi"
    label: "Demografi"
    folder: "content/demografi"
    create: false
    identifier_field: name
    media_folder: "/static/images/demografi"
    public_folder: "images/demografi"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}
      - label : "Data Desa"
        name  : "dusun_banjeng"
        widget: "list"
        fields:
          - {label: "Nama Data", name: "name", widget: "string"}
          - {label: "Jumlah Data", name: "count", widget: "number"}
      - label : "Data Desa"
        name  : "dusun_tempelsari"
        widget: "list"
        fields:
          - {label: "Nama Data", name: "name", widget: "string"}
          - {label: "Jumlah Data", name: "count", widget: "number"}
      - label : "Data Desa"
        name  : "dusun_grogol"
        widget: "list"
        fields:
          - {label: "Nama Data", name: "name", widget: "string"}
          - {label: "Jumlah Data", name: "count", widget: "number"}
      - label : "Data Desa"
        name  : "dusun_bokoharjo"
        widget: "list"
        fields:
          - {label: "Nama Data", name: "name", widget: "string"}
          - {label: "Jumlah Data", name: "count", widget: "number"}
      - label : "Data Desa"
        name  : "perumahan_ayodya_citra"
        widget: "list"
        fields:
          - {label: "Nama Data", name: "name", widget: "string"}
          - {label: "Jumlah Data", name: "count", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "visimisi"
    label: "Visi Misi"
    folder: "content/visimisi"
    create: false
    identifier_field: name
    media_folder: "/static/images/visimisi"
    public_folder: "images/visimisi"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}

  - name: "kepaladukuh"
    label: "Kepala Dukuh"
    folder: "content/kepaladukuh"
    create: false
    identifier_field: name
    media_folder: "/static/images/kepaladukuh"
    public_folder: "images/kepaladukuh"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}

  - name: "literasi"
    label: "Literasi"
    folder: "content/literasi"
    create: false
    identifier_field: name
    media_folder: "/static/images/literasi"
    public_folder: "images/literasi"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}

  - name: "kampungkb"
    label: "Kampung KB"
    folder: "content/kampungkb"
    create: false
    identifier_field: name
    media_folder: "/static/images/kampungkb"
    public_folder: "images/kampungkb"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}

  - name: "posyandu"
    label: "Posyandu"
    folder: "content/posyandu"
    create: false
    identifier_field: name
    media_folder: "/static/images/posyandu"
    public_folder: "images/posyandu"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}

  - name: "perikanan"
    label: "Perikanan"
    folder: "content/perikanan"
    create: false
    identifier_field: name
    media_folder: "/static/images/perikanan"
    public_folder: "images/perikanan"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}

  - name: "taman"
    label: "Taman"
    folder: "content/taman"
    create: false
    identifier_field: name
    media_folder: "/static/images/taman"
    public_folder: "images/taman"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}

  - name: "perternakan"
    label: "Perternakan"
    folder: "content/perternakan"
    create: false
    identifier_field: name
    media_folder: "/static/images/perternakan"
    public_folder: "images/perternakan"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}

  - name: "umkm"
    label: "UMKM"
    folder: "content/umkm"
    create: false
    identifier_field: name
    media_folder: "/static/images/umkm"
    public_folder: "images/umkm"
    fields:
      - {label: "Halaman Tentang", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Gambar Thumbnail", name: "image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}