---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin-forestry"
webhook_url: 
sections:
- type: directory
  path: content/about
  label: Tentang
  create: none
  match: "**/*"
- type: directory
  path: content/staff
  label: Staff
  create: all
  match: "**/*"
  templates:
  - template-staff
- type: directory
  path: content/pasar
  label: Pasar
  create: all
  match: "**/*"
  templates:
  - template-pasar
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
  templates:
  - template-kontak
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - template
- type: directory
  path: content/acara
  label: Acara
  create: all
  match: "**/*"
- type: heading
  label: Konfigurasi
- type: document
  path: config.yaml
  label: Konfigurasi
- type: directory
  path: data
  label: Data
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
