---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin-forestry"
webhook_url: 
sections:
- type: heading
  label: Profil
- type: directory
  path: content/demografi
  label: Demografi
  create: none
  match: "**/*"
- type: directory
  path: content/visimisi
  label: Visi Misi
  create: none
  match: "**/*"
- type: directory
  path: content/kepaladukuh
  label: Kepala Dukuh
  create: none
  match: "**/*"
- type: heading
  label: Inovasi Desa
- type: directory
  path: content/literasi
  label: Literasi
  create: none
  match: "**/*"
- type: directory
  path: content/kampungkb
  label: Kampung KB
  create: none
  match: "**/*"
- type: directory
  path: content/posyandu
  label: Posyandu
  create: none
  match: "**/*"
- type: directory
  path: content/perikanan
  label: Perikanan
  create: none
  match: "**/*"
- type: directory
  path: content/taman
  label: Taman
  create: none
  match: "**/*"
- type: directory
  path: content/perternakan
  label: Perternakan
  create: none
  match: "**/*"
- type: directory
  path: content/umkm
  label: UMKM
  create: none
  match: "**/*"
- type: heading
  label: Galeri
- type: directory
  path: content/dusunbanjeng
  label: Dusun Banjeng
  create: none
  match: "**/*"
- type: directory
  path: content/dusuntempelsari
  label: Dusun Tempelsari
  create: none
  match: "**/*"
- type: directory
  path: content/dusungrogol
  label: Dusun Grogol
  create: none
  match: "**/*"
- type: directory
  path: content/dusunbokoharjo
  label: Dusun Bokoharjo
  create: none
  match: "**/*"
- type: directory
  path: content/ayodyacitra
  label: Ayodya Citra
  create: none
  match: "**/*"
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - template
- type: heading
  label: Konfigurasi
- type: document
  path: config.yaml
  label: Konfigurasi
- type: directory
  path: data
  label: Data
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
